name: student_mg
description: "Ứng dụng quản lý sinh viên bằng Flutter + Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_ui_auth: ^3.0.0

  # Navigation & State Management
  go_router: ^16.2.4
  provider: ^6.1.5+1
  fl_chart: ^1.1.1
  # Utilities
  uuid: ^4.5.1
  flutter_dotenv: ^5.1.0
  firebase_ui_firestore: ^2.0.0
  firebase_pagination: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets phải được thụt lề vào trong mục flutter
  assets:
    - .env

  # Ví dụ về cách thêm các tài nguyên khác:
  # assets:
  #   - .env
  #   - assets/images/logo.png
  #   - assets/data/config.json

  # Để thêm phông chữ tùy chỉnh, hãy thêm mục fonts tại đây.
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
